version: '1'
services:
  users-service:
    build: ./users-service
    container_name: users_service
    ports:
     - "4000:4000"
    links:
      - mysqldb:mysqldb
    depends_on:
     - mysqldb
    environment:
     - DATABASE_HOST=mysqldb
  db:
    build: ./database
