version: '3.2'
services:
  users-service:
    container_name: users_service
    build: ./users-service
    ports:
     - "4000:4000"
    links:
      - users-database:users-database
    depends_on:
     - users-database
    environment:
     - DATABASE_HOST=users-database
  users-database:
    container_name: users_database
    build: ./users-database
